[[38;2;128;05;128m2025-09-16 13:47:38,051[0m] [38;2;255;160;0m WARNING[0m[38;2;112;128;144m    viperlog: [0m Unsupported units found for column/variable TIME: ['dubious/units']. Cannot create an astropy.units.Units object from it: 'dubious/units' did not parse as unit: At col 0, dubious is not a valid unit.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html 
[[38;2;128;05;128m2025-09-16 13:47:38,051[0m] [38;2;255;160;0m WARNING[0m[38;2;112;128;144m    viperlog: [0m Invalid units found for column/variable DATA: (None, None) 
[[38;2;128;05;128m2025-09-16 13:47:38,051[0m] [38;2;255;160;0m WARNING[0m[38;2;112;128;144m    viperlog: [0m Unsupported units found for column/variable DATA: (None, None). Cannot create an astropy.units.Units object from it: None cannot be converted to a Unit 
[[38;2;128;05;128m2025-09-16 13:47:38,051[0m] [38;2;255;160;0m WARNING[0m[38;2;112;128;144m    viperlog: [0m Invalid units found for column/variable TIME_CENTROID: (3.1,) 
