{"name": "test_get_freq_axis_empty", "status": "passed", "description": "Test that get_freq_axis raises an exception on empty DataTree", "start": 1757016773827, "stop": 1757016773827, "uuid": "2bca56ae-c00b-4e1f-8829-744bc3cd8eba", "historyId": "189434fe6bfe4f209b79e11ce2ab584c", "testCaseId": "189434fe6bfe4f209b79e11ce2ab584c", "fullName": "tests.unit.measurement_set.test_processing_set_xdt.TestProcessingSetXdtErrors#test_get_freq_axis_empty", "labels": [{"name": "parentSuite", "value": "tests.unit.measurement_set"}, {"name": "suite", "value": "test_processing_set_xdt"}, {"name": "subSuite", "value": "TestProcessingSetXdtErrors"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "3826-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.measurement_set.test_processing_set_xdt"}], "titlePath": ["tests", "unit", "measurement_set", "test_processing_set_xdt.py", "TestProcessingSetXdtErrors"]}