{"name": "test_query_empty", "status": "passed", "description": "Test that query raises an exception on empty DataTree", "start": 1757016773829, "stop": 1757016773829, "uuid": "b99b73bd-4263-4ade-96f0-92ea6bce846d", "historyId": "25c87d75b86187bf483083515b180d16", "testCaseId": "25c87d75b86187bf483083515b180d16", "fullName": "tests.unit.measurement_set.test_processing_set_xdt.TestProcessingSetXdtErrors#test_query_empty", "labels": [{"name": "parentSuite", "value": "tests.unit.measurement_set"}, {"name": "suite", "value": "test_processing_set_xdt"}, {"name": "subSuite", "value": "TestProcessingSetXdtErrors"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "3826-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.measurement_set.test_processing_set_xdt"}], "titlePath": ["tests", "unit", "measurement_set", "test_processing_set_xdt.py", "TestProcessingSetXdtErrors"]}