{"name": "test_summary_empty", "status": "passed", "description": "Test that summary raises an exception on empty DataTree", "start": 1757016773824, "stop": 1757016773824, "uuid": "cd212f80-f474-478e-8b2a-4ca0e06a0da0", "historyId": "7f43d11dca99d6518d4939a4e3852abc", "testCaseId": "7f43d11dca99d6518d4939a4e3852abc", "fullName": "tests.unit.measurement_set.test_processing_set_xdt.TestProcessingSetXdtErrors#test_summary_empty", "labels": [{"name": "parentSuite", "value": "tests.unit.measurement_set"}, {"name": "suite", "value": "test_processing_set_xdt"}, {"name": "subSuite", "value": "TestProcessingSetXdtErrors"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "3826-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.measurement_set.test_processing_set_xdt"}], "titlePath": ["tests", "unit", "measurement_set", "test_processing_set_xdt.py", "TestProcessingSetXdtErrors"]}