{"name": "test_get_combined_antenna", "status": "passed", "description": "Test that get_combined_antenna_xds raises an exception on empty DataTree", "start": 1757016773830, "stop": 1757016773830, "uuid": "28f2f0ad-5057-44a8-988a-a16f096bb7f1", "historyId": "20e61705a966f86b71c83a844f2008b1", "testCaseId": "20e61705a966f86b71c83a844f2008b1", "fullName": "tests.unit.measurement_set.test_processing_set_xdt.TestProcessingSetXdtErrors#test_get_combined_antenna", "labels": [{"name": "parentSuite", "value": "tests.unit.measurement_set"}, {"name": "suite", "value": "test_processing_set_xdt"}, {"name": "subSuite", "value": "TestProcessingSetXdtErrors"}, {"name": "host", "value": "pkrvm7jw40e0xgp"}, {"name": "thread", "value": "3826-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.measurement_set.test_processing_set_xdt"}], "titlePath": ["tests", "unit", "measurement_set", "test_processing_set_xdt.py", "TestProcessingSetXdtErrors"]}